pizzas/urls.py
from django.urls import path

from . import views

app_name = 'pizzas'

urlpatterns = [
    path('', views.index, name='index'),
    path('pizzas', views.pizzas, name='pizzas'),
    path('pizzas/<int:pizza_id>/', views.pizza, name='pizza'),
    path('new_comment/<int:pizza_id>/', views.new_comment, name='new_comment'),
    
]

pizzeria/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pizzas.urls')),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pizzas/models.py
from django.db import models

# Create your models here.

class Pizza(models.Model):
    name = models.CharField(max_length=200)
    image = models.ImageField(upload_to='images/', null=True)

    def __str__(self):
        return self.name


class Topping(models.Model):
    pizza = models.ForeignKey(Pizza, on_delete=models.CASCADE)
    name = models.TextField()

    def __str__(self):
        return self.name


class Comment(models.Model):
    pizza = models.ForeignKey(Pizza, on_delete=models.CASCADE)
    comment = models.TextField()

    def __str__(self):
        return self.comment

pizzas/forms.py
from django import forms
from .models import Comment

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['comment']
        label = {'Comment: ':''}

pizzas/views.py
from django.shortcuts import render, redirect
from .models import Pizza, Topping, Comment
from .forms import CommentForm

# Create your views here.

def index(request):
    ''' The home page for da pizzas. '''
    return render(request, 'pizzas/index.html')

def pizzas(request):
    pizzas = Pizza.objects.all()

    context = {'pizzas':pizzas}
    return render(request, 'pizzas/pizzas.html', context)


def pizza(request, pizza_id):
    pizza = Pizza.objects.get(id = pizza_id)
    toppings = pizza.topping_set.order_by('name')
    comments = pizza.comment_set.order_by('comment')

    context = {'pizza':pizza, 'toppings':toppings, 'comments':comments}

    return render(request, 'pizzas/pizza.html', context)


def new_comment(request, pizza_id):
    pizza = Pizza.objects.get(id=pizza_id)

    if request.method != 'POST':
        form = CommentForm()
    else:
        form = CommentForm(data=request.POST)

        if form.is_valid():
            new_comment = form.save(commit=False)
            new_comment.pizza = pizza
            new_comment.save()
            form.save()

            return redirect('pizzas:pizza', pizza_id=pizza_id)
    context = {'form':form, 'pizza':pizza}
    return render(request, 'pizzas/new_comment.html', context)

pizzas/templates/pizzas/base.html
{% load static %}

<p>
    <a href="{% url 'pizzas:index' %}"><img src="{% static 'pizzas/images/logo.jpg' %}"></a>
    <a href="{% url 'pizzas:pizzas' %}"><img src="{% static 'pizzas/images/slice.jpg' %}" width="150" height="150"></a>

</p>

{% block content %}

{% endblock content %}

pizzas/templates/pizzas/index.html
{% extends "pizzas/base.html" %}

{% load static %}

{% block content %}



<p> Flippin' Pizza: We put the 'pizza' in 'pizzazz'
</p>

<p> Click on the slice to get started!</p>

{% endblock content %}

pizzas/templates/pizzas/new_comment.html
{% extends "pizzas/base.html" %}

{% block content %}

<p> <a href="{% url 'pizzas:pizza' pizza.id %}">{{ pizza }}</a></p>

<p> Add a new comment: </p>

<form action="{% url 'pizzas:new_comment' pizza.id %}" method='post'>

    {% csrf_token %}

    {{ form.as_p }}

    <button name="submit">Add comment</button>

</form>

{% endblock content %}

pizzas/templates/pizzas/pizza.html
{% extends "pizzas/base.html" %}

{% block content %}

<p>Pizza: {{ pizza }}</p>

<p><img src="{{ pizza.image.url }}" width="200" height="200"></p>

<p>Toppings</p>

<ul>
    {% for topping in toppings %}
    <li>
        <p> {{topping}}</p>
    </li>
    {% empty %}
    <li>This pizza has no toppings.</li>
    {% endfor %}
</ul>


<p>Comments</p>

<p><a href="{% url 'pizzas:new_comment' pizza.id %}">Add a new comment</a></p>

<ul>
    {% for comment in comments %}
    <li>
        <p> {{comment}}</p>
    </li>
    {% empty %}
    <li>This pizza has no comments - yet.</li>
    {% endfor %}
</ul>

{% endblock content %}

pizzas/templates/pizzas/pizzas.html
{% extends "pizzas/base.html" %}

{% block content %}

<p>Pizzas</p>

<ul>
    {% for pizza in pizzas %}
    <li>
        <a href="{% url 'pizzas:pizza' pizza.id %}">{{pizza}}</a>
    </li>
    {% empty %}
    <li> No pizzas are here - yet.</li>
    {% endfor %}
</ul>

{% endblock content %}